#!/bin/bash
# Download media.xml using wget.

file="${1-media.xml}"
url="${2-http://xml.election-montreal.qc.ca/media.xml}"
repo="${3-history}"

mkdir -p "$repo" # Please 'git init . && git add media.xml' manually if you want to preserve history.

echo "Downloading to $repo/media.xml: $url"
wget --quiet -O "$repo/media.xml" "$url"
git --git-dir="$repo/.git" --work-tree="$repo" commit -a -m "Download $file"
cp -v "$file" "$file.old"
cp -v "$repo/media.xml" "$file"

script/xml_to_json "$file" > "$file.json"
