#!/usr/bin/env ruby
require 'rexml/document'

file = File.new(ARGV[0])
doc = REXML::Document.new(file.read)

doc.root.each_element('//arrondissement') do |tag|
  @arr = Arrondissement.find_or_initialize_by_mtl_id tag.attributes['id']
  if @arr.new_record?
    @arr.nom = tag.text
    @arr.save!
    puts @arr.inspect
  end
end

doc.root.each_element('//parti') do |tag|
  @arr = Parti.find_or_initialize_by_mtl_id tag.attributes['id']
  if @arr.new_record?
    @arr.nom = tag.text
    @arr.save!
    puts @arr.inspect
  end
end

doc.root.each_element('//district') do |tag|
  @arr = District.find_or_initialize_by_mtl_id tag.attributes['id']
  if @arr.new_record?
    @arr.nom = tag.text
    @arr.save!
    puts @arr.inspect
  end
end

doc.root.each_element('//resultats_maire/sommaire/candidat') do |tag|
  @maire = CandidatMaire.new
  #@maire.update_attributes tag.elements.to_hash {|e| [e.name, e.text] }
  ['nom', 'prenom', 'nb_voix_obtenues', 'nb_voix_majorite'].each do |attry|
    @maire.update_attribute attry, tag.elements[attry].text
  end
  @maire.mtl_id = tag.attributes['id']
  @maire.parti = Parti.find_by_mtl_id(tag.elements['parti'].attributes['id'])
  @maire.save!
  puts @maire.inspect
end

